[package]
name = "mukta-chain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bcrypt = "0.15.1"
uuid = {version = "*", features = ["v4"]}
web3 = "0.19.0"
